export const icons: { [key: string]: any } = {
    dashboard: require("../assets/icons/dashboard.png"),
    fleet: require("../assets/icons/fleet.png"),
    drivers: require("../assets/icons/drivers.png"),
    routes: require("../assets/icons/routes.png"),
    settings: require("../assets/icons/settings.png"),
    notifications: require("../assets/icons/notifications.png"),
    google: require("../assets/icons/google.png"),
    apple: require("../assets/icons/apple.png"),
    logout: require("../assets/icons/logout.png"),
    active: require("../assets/icons/active.png"),
    inactive: require("../assets/icons/inactive.png"),
    add: require("../assets/icons/add.png"),
    mail: require("../assets/icons/mail.png"),
    phone: require("../assets/icons/phone.png"),
    calendar: require("../assets/icons/calendar.png"),
    pen: require("../assets/icons/pen.png"),
    trash: require("../assets/icons/trash.png"),
    repair: require("../assets/icons/repair.png"),
    up: require("../assets/icons/up.png"),
    down: require("../assets/icons/down.png"),
    search: require("../assets/icons/search.png"),
}