name: Notify Telegram on Workflow Completion

on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Telegram
        run: |
          curl -s -X POST \
          "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="✅ Workflow '${{ github.workflow }}' completed! 
          🔗 View logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
